//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageCRUDInDatabaseFirstApproachUsingEntityFramwork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        public int Id { get; set; }
        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Employee Name is Required")]
        public string Name { get; set; }
        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Employee Designation is Required")]
        public string Designation { get; set; }
        [DisplayName("Employee Image")]
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
